In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
sns.set()
%matplotlib inline
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import statsmodels.api as sm
from xgboost import XGBRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer
import warnings
# import the_module_that_warns

warnings.filterwarnings("ignore")

from fbprophet import Prophet

In [3]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
sample_df = pd.read_csv('sample_submission.csv')

In [4]:
import keras

Using TensorFlow backend.

In [5]:
train_df

,id,2009-01,2009-02,2009-03,2009-04,2009-05,2009-06,2009-07,2009-08,2009-09,...,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05
0,0,26.68,11.86,19.77,14.83,7.90,2.96,5.93,4.94,4.94,...,1.97,0.98,2.96,4.94,6.91,9.88,0.00,2.96,7.90,4.94
1,1,107.73,77.09,79.09,4.94,48.44,22.74,33.61,23.72,23.72,...,11.85,11.85,19.76,22.73,38.54,145.28,56.33,62.26,58.31,32.61
2,2,94.88,90.93,78.10,66.24,38.55,25.70,27.68,26.69,18.78,...,0.00,0.00,0.00,0.00,81.04,130.45,71.15,0.00,0.00,0.00
3,3,0.00,0.00,149.29,51.41,6.92,8.89,2.96,2.96,1.97,...,0.00,0.00,5.92,26.68,74.12,158.12,159.11,105.75,86.97,43.48
4,4,97.85,97.85,70.19,60.31,31.63,25.70,20.76,22.74,20.76,...,8.89,8.89,16.80,22.73,20.75,26.68,32.61,19.76,21.74,15.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78582,78582,123.55,129.48,91.94,50.42,26.69,8.89,6.92,4.94,3.95,...,9.88,12.84,29.64,38.54,57.32,92.90,81.04,70.17,56.33,39.53
78583,78583,15.81,0.00,0.00,88.98,176.97,40.53,14.83,13.84,19.77,...,19.76,20.75,23.71,33.60,60.28,46.45,53.36,36.57,44.47,29.65
78584,78584,36.57,25.69,7.90,8.89,5.93,4.94,4.94,3.95,4.94,...,4.94,3.95,5.92,6.91,6.91,18.77,22.73,17.79,9.88,6.91
78585,78585,196.69,198.66,157.20,140.39,85.02,51.41,34.60,26.69,26.69,...,10.87,12.84,21.74,61.27,83.01,184.81,156.15,100.81,91.92,39.53
78586,78586,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.97,...,2.96,8.89,62.26,0.00,28.66,55.34,50.40,65.23,0.00,0.00

In [18]:
test_df.drop(['id'], axis = 1, inplace = True)

In [22]:
test_df

,2009-01,2009-02,2009-03,2009-04,2009-05,2009-06,2009-07,2009-08,2009-09,2009-10,...,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05
0,74.13,93.89,79.09,59.32,29.66,19.77,14.83,14.83,14.83,10.87,...,12.84,9.88,14.82,27.66,66.20,83.98,93.86,79.06,53.36,33.60
1,41.51,53.37,43.50,34.60,25.70,17.79,11.86,11.86,9.88,10.87,...,10.86,8.89,9.88,23.71,44.46,82.01,92.88,79.06,55.34,26.68
2,82.03,86.97,81.07,58.33,41.52,19.77,9.88,12.85,9.88,14.83,...,7.90,7.90,10.86,20.75,59.28,81.02,92.88,69.18,38.54,14.82
3,89.94,80.06,107.76,62.28,25.70,20.76,19.77,18.78,30.64,0.00,...,7.90,9.88,12.84,8.89,34.58,64.22,64.22,64.23,49.41,39.53
4,17.79,19.76,20.76,26.69,28.67,32.62,20.76,9.88,10.87,11.86,...,14.82,13.83,15.80,23.71,60.27,83.98,82.01,88.94,57.32,22.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,197.68,142.32,69.20,108.75,32.62,19.77,19.77,18.78,10.87,17.79,...,8.89,13.83,16.79,28.65,86.95,178.84,167.97,119.58,79.06,35.57
9996,134.42,132.44,76.12,66.24,33.61,21.75,15.81,15.81,12.85,16.80,...,4.94,7.90,7.90,44.46,119.56,222.32,249.98,211.49,114.64,52.37
9997,74.13,69.18,34.60,21.75,18.78,8.89,20.76,0.00,0.00,0.00,...,1.97,0.98,3.95,8.89,15.80,35.57,38.53,11.85,12.84,8.89
9998,24.71,25.69,19.77,13.84,8.89,8.89,8.89,8.89,10.87,6.92,...,4.94,2.96,2.96,8.89,49.40,49.40,78.05,64.23,37.55,11.85
9999,190.76,136.39,113.70,75.14,43.50,30.64,23.72,25.70,19.77,21.75,...,4.94,6.91,8.89,18.77,105.72,127.46,135.36,87.95,26.68,9.88